### ISSUE TITLE
Debugging doesn't work

### ISSUE THREAD

**Issue by oli-unreal** [jenkinsci/gradle-jpi-plugin#170] opened 2020-11-03 16:09 UTC
With version 0.39.0, running `./gradlew server -Dorg.gradle.debug=true` give me this:
```
Starting a Gradle Daemon, 1 incompatible Daemon could not be reused, use --status for details

> Starting Daemon
```
It is stuck there.

On version 0.40.0-rc-2 it give me a weirder bug on ` ./gradlew server --debug-jvm` :
```
2020-11-03 16:04:49.010+0000 [id=47]    SEVERE  jenkins.InitReactorRunner$1#onTaskFailed: Failed Inspecting plugin /tmp/jenkins/plugins/eos-scm.hpl
java.io.IOException: No such file: /root/.gradle/caches/modules-2/files-2.1/com.squareup.okhttp3/okhttp/4.5.0/cfd127ae6de4862daa93e15ceae9291108eaabc5/okhttp-4.5.0.jar
        at hudson.ClassicPluginStrategy.parseClassPath(ClassicPluginStrategy.java:461)
        at hudson.ClassicPluginStrategy.createPluginWrapper(ClassicPluginStrategy.java:202)
        at hudson.PluginManager$1$3$1.run(PluginManager.java:436)
        at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
        at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
        at jenkins.model.Jenkins$5.runTask(Jenkins.java:1131)
        at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
        at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
        at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```
An instance of jenkins was created, but my plugin wasn't loaded.

**Comment by sghill** [comment] 2020-11-04 18:48
Hi @oli-unreal, thank you for the report.

The `0.39.0` version of the plugin needs the `--no-daemon` flag (#151).
The `server` task has been rewritten for `0.40.x`. 

Could you provide a small example that reproduces the problem? Jenkins version and Gradle version would also be helpful.

**Comment by oli-unreal** [comment] 2020-11-04 21:11
With this sample: https://github.com/martinda/simple-scm-plugin It works on `0.40.0`, so I will try to see what config make it broke. But it still fails with `0.39.0` with the same error even with the `--no-daemon`

The build.gradle.kts with jenkins at 2.249.1 and gradle at 6.4.1
```
import org.jenkinsci.gradle.plugins.jpi.JpiDeveloper
import org.jenkinsci.gradle.plugins.jpi.JpiLicense

plugins {
    "java-library"
    // id("org.jenkins-ci.jpi") version "0.40.0-rc.2"
   id("org.jenkins-ci.jpi") version "0.39.0"
}

repositories {
    maven {
        url = uri("https://repo.jenkins-ci.org/public/")
    }
	jcenter()
}

group = "org.jenkins-ci.plugins"
version = "1.2.0-SNAPSHOT"
description = "A description of your plugin"

val jenkinsCoreVersion: String by project

jenkinsPlugin {
    coreVersion = jenkinsCoreVersion
    compatibleSinceVersion = coreVersion
    shortName = "jenkins-scm"
    displayName = "Demo plugin built with Gradle"
    url = "http://wiki.jenkins-ci.org/display/JENKINS/SomePluginPage"
    gitHubUrl = "https://github.com/jenkinsci/some-plugin"
    pluginFirstClassLoader = true
    maskClasses = "groovy.grape org.apache.commons.codec"
    workDir = file("/tmp/jenkins")
    repoUrl = "https://repo.jenkins-ci.org/releases"
    snapshotRepoUrl = "https://repo.jenkins-ci.org/snapshots"
    disabledTestInjection = false
    configureRepositories = false
    configurePublishing = false
    fileExtension = "hpi"
}
```

**Comment by sghill** [comment] 2020-12-10 03:28
Since it's working on 0.40.x, I'm going to close this one out. I'll get the 0.40.0 release out in the next week or so.

Feel free to reopen if certain config makes it not work on 0.40.x.

**Closed by sghill** 2020-12-10 03:28 UTC
